//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyBot.ResourceStats", typeof(ResourceStats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Accuracy.
        /// </summary>
        public static string AverageAccuracy {
            get {
                return ResourceManager.GetString("AverageAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Combo.
        /// </summary>
        public static string AverageCombo {
            get {
                return ResourceManager.GetString("AverageCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average GPS.
        /// </summary>
        public static string AverageGPS {
            get {
                return ResourceManager.GetString("AverageGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Misses.
        /// </summary>
        public static string AverageMisses {
            get {
                return ResourceManager.GetString("AverageMisses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating.
        /// </summary>
        public static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Score.
        /// </summary>
        public static string AverageScore {
            get {
                return ResourceManager.GetString("AverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Accuracy.
        /// </summary>
        public static string HighestAccuracy {
            get {
                return ResourceManager.GetString("HighestAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on the map {1} - {2} [{3}] ({4}*) with {5:n0} Points and {6}% Accuracy!.
        /// </summary>
        public static string HighestAccuracyMap {
            get {
                return ResourceManager.GetString("HighestAccuracyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Average Accuracy.
        /// </summary>
        public static string HighestAvgAccuracy {
            get {
                return ResourceManager.GetString("HighestAvgAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Average Score.
        /// </summary>
        public static string HighestAvgScore {
            get {
                return ResourceManager.GetString("HighestAvgScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match MVPs.
        /// </summary>
        public static string MatchMVPs {
            get {
                return ResourceManager.GetString("MatchMVPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find match .
        /// </summary>
        public static string MatchNotFound {
            get {
                return ResourceManager.GetString("MatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match played at.
        /// </summary>
        public static string MatchPlayed {
            get {
                return ResourceManager.GetString("MatchPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Valuable Player.
        /// </summary>
        public static string MVP {
            get {
                return ResourceManager.GetString("MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Rating.
        /// </summary>
        public static string OverallRating {
            get {
                return ResourceManager.GetString("OverallRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find player .
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats For.
        /// </summary>
        public static string StatsFor {
            get {
                return ResourceManager.GetString("StatsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team MVP: .
        /// </summary>
        public static string TeamMVP {
            get {
                return ResourceManager.GetString("TeamMVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find team .
        /// </summary>
        public static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Rating.
        /// </summary>
        public static string TeamRating {
            get {
                return ResourceManager.GetString("TeamRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} won! ({1}:{2}).
        /// </summary>
        public static string TeamWon {
            get {
                return ResourceManager.GetString("TeamWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
    }
}
