//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        internal static string BlueLower {
            get {
                return ResourceManager.GetString("BlueLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannnot be null or empty.
        /// </summary>
        internal static string CannotBeNullEmptyException {
            get {
                return ResourceManager.GetString("CannotBeNullEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or empty.
        /// </summary>
        internal static string CannotBeNullOrEmptyException {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot Token cannot be null, empty or less than 10 long.
        /// </summary>
        internal static string DiscordTokenEmptyNullShort {
            get {
                return ResourceManager.GetString("DiscordTokenEmptyNullShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch from osu! api, please retry in a moment, if this keeps happening contact ??????#0284 (discord).
        /// </summary>
        internal static string FailedFetchOsuApi {
            get {
                return ResourceManager.GetString("FailedFetchOsuApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Accuracy.
        /// </summary>
        internal static string HighestAccuracy {
            get {
                return ResourceManager.GetString("HighestAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        internal static string HighestScore {
            get {
                return ResourceManager.GetString("HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Valuable Player.
        /// </summary>
        internal static string MVP {
            get {
                return ResourceManager.GetString("MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BanchoBot.
        /// </summary>
        internal static string OsuIrcBotName {
            get {
                return ResourceManager.GetString("OsuIrcBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        internal static string RedLower {
            get {
                return ResourceManager.GetString("RedLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue.
        /// </summary>
        internal static string TeamBlue {
            get {
                return ResourceManager.GetString("TeamBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red.
        /// </summary>
        internal static string TeamRed {
            get {
                return ResourceManager.GetString("TeamRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} won! ({1}:{2}).
        /// </summary>
        internal static string TeamWonWithPoins {
            get {
                return ResourceManager.GetString("TeamWonWithPoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be zero.
        /// </summary>
        internal static string TimeZeroException {
            get {
                return ResourceManager.GetString("TimeZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code or verification not found.
        /// </summary>
        internal static string VerCodeInvalidNotFound {
            get {
                return ResourceManager.GetString("VerCodeInvalidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully verified.
        /// </summary>
        internal static string VerSuccess {
            get {
                return ResourceManager.GetString("VerSuccess", resourceCulture);
            }
        }
    }
}
