//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level.
        /// </summary>
        public static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough permissions to use this command.
        /// </summary>
        public static string AccessTooLow {
            get {
                return ResourceManager.GetString("AccessTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string BlueLower {
            get {
                return ResourceManager.GetString("BlueLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot info for .
        /// </summary>
        public static string BotInfoFor {
            get {
                return ResourceManager.GetString("BotInfoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannnot be null or empty.
        /// </summary>
        public static string CannotBeNullEmptyException {
            get {
                return ResourceManager.GetString("CannotBeNullEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or empty.
        /// </summary>
        public static string CannotBeNullOrEmptyException {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Servers.
        /// </summary>
        public static string DiscordGuilds {
            get {
                return ResourceManager.GetString("DiscordGuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Bot Token cannot be null, empty or less than 10 long.
        /// </summary>
        public static string DiscordTokenEmptyNullShort {
            get {
                return ResourceManager.GetString("DiscordTokenEmptyNullShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch from osu! api, please retry in a moment, if this keeps happening contact ??????#0284 (discord).
        /// </summary>
        public static string FailedFetchOsuApi {
            get {
                return ResourceManager.GetString("FailedFetchOsuApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse {0}.
        /// </summary>
        public static string FailedParseException {
            get {
                return ResourceManager.GetString("FailedParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string FalseLower {
            get {
                return ResourceManager.GetString("FalseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Accuracy.
        /// </summary>
        public static string HighestAccuracy {
            get {
                return ResourceManager.GetString("HighestAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Score.
        /// </summary>
        public static string HighestScore {
            get {
                return ResourceManager.GetString("HighestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‎.
        /// </summary>
        public static string InvisibleCharacter {
            get {
                return ResourceManager.GetString("InvisibleCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Valuable Player.
        /// </summary>
        public static string MVP {
            get {
                return ResourceManager.GetString("MVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough parameters, please recheck the command.
        /// </summary>
        public static string NotEnoughParameters {
            get {
                return ResourceManager.GetString("NotEnoughParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BanchoBot.
        /// </summary>
        public static string OsuIrcBancho {
            get {
                return ResourceManager.GetString("OsuIrcBancho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string RedLower {
            get {
                return ResourceManager.GetString("RedLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Blue.
        /// </summary>
        public static string TeamBlue {
            get {
                return ResourceManager.GetString("TeamBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Red.
        /// </summary>
        public static string TeamRed {
            get {
                return ResourceManager.GetString("TeamRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team {0} won! ({1}:{2}).
        /// </summary>
        public static string TeamWonWithPoins {
            get {
                return ResourceManager.GetString("TeamWonWithPoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be zero.
        /// </summary>
        public static string TimeZeroException {
            get {
                return ResourceManager.GetString("TimeZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string TrueLower {
            get {
                return ResourceManager.GetString("TrueLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        public static string Uptime {
            get {
                return ResourceManager.GetString("Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code or verification not found.
        /// </summary>
        public static string VerCodeInvalidNotFound {
            get {
                return ResourceManager.GetString("VerCodeInvalidNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Users.
        /// </summary>
        public static string VerifiedUsers {
            get {
                return ResourceManager.GetString("VerifiedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully verified.
        /// </summary>
        public static string VerSuccess {
            get {
                return ResourceManager.GetString("VerSuccess", resourceCulture);
            }
        }
    }
}
