// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.AccessLevelCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.HelpCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.HelpCommand.ShowHelp(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.HelpCommand.ShowHelp(DSharpPlus.Entities.DiscordChannel,SkyBot.Discord.CommandSystem.ICommand,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.VerificationCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.WarmupCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.SyncRolesCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.RemoveMatchCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.RemindMeCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.RemindMeCommand.Finalize")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.RemindMeCommand.OnRemindMeTimerElapsed(System.Object,System.Timers.ElapsedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.PrivacyPolicyCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.NotifyHostsCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.MaintenanceCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.ConfigCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.BWSCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.PermissionCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.StatsCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.TicketCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.SyncCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.UserInfoCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.UserInfoCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.ClearMatchesCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:DiscordCommands.EmbedCommand.Invoke(SkyBot.Discord.CommandSystem.CommandHandler,SkyBot.Discord.CommandSystem.CommandEventArg)")]
