//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordCommands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordCommands.ResourcesCommands", typeof(ResourcesCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accesslevel.
        /// </summary>
        internal static string AccessLevelCommand {
            get {
                return ResourceManager.GetString("AccessLevelCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows or sets your accesslevel.
        /// </summary>
        internal static string AccessLevelCommandDescription {
            get {
                return ResourceManager.GetString("AccessLevelCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host can add more admins!.
        /// </summary>
        internal static string AccessLevelCommandHostOnlyAddAdmins {
            get {
                return ResourceManager.GetString("AccessLevelCommandHostOnlyAddAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be atleast Host to set someone to host!.
        /// </summary>
        internal static string AccessLevelCommandHostOnlyAddHost {
            get {
                return ResourceManager.GetString("AccessLevelCommandHostOnlyAddHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev permission can only be set via db.
        /// </summary>
        internal static string AccessLevelCommandSetDevPermission {
            get {
                return ResourceManager.GetString("AccessLevelCommandSetDevPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} from {1} to {2}.
        /// </summary>
        internal static string AccessLevelCommandSetPermission {
            get {
                return ResourceManager.GetString("AccessLevelCommandSetPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}accesslevel
        ///{prefix}accesslevel &lt;userId&gt;
        ///Admin:
        ///{prefix}accesslevel &lt;userId&gt; &lt;new level (User, VIP, Moderator, Admin, Host, Dev)&gt;.
        /// </summary>
        internal static string AccessLevelCommandUsage {
            get {
                return ResourceManager.GetString("AccessLevelCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} your access level is {1}.
        /// </summary>
        internal static string AccessLevelCommandUser {
            get {
                return ResourceManager.GetString("AccessLevelCommandUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access level of user {0} is {1}.
        /// </summary>
        internal static string AccessLevelCommandUserOther {
            get {
                return ResourceManager.GetString("AccessLevelCommandUserOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bws.
        /// </summary>
        internal static string BWSCommand {
            get {
                return ResourceManager.GetString("BWSCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates the bws rank.
        /// </summary>
        internal static string BWSCommandDescription {
            get {
                return ResourceManager.GetString("BWSCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the badge count {0}.
        /// </summary>
        internal static string BWSCommandFailedParseBadgeCount {
            get {
                return ResourceManager.GetString("BWSCommandFailedParseBadgeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the rank {0}.
        /// </summary>
        internal static string BWSCommandFailedParseRank {
            get {
                return ResourceManager.GetString("BWSCommandFailedParseRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} BWS: {1}.
        /// </summary>
        internal static string BWSCommandResult {
            get {
                return ResourceManager.GetString("BWSCommandResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}bws &lt;rank&gt; &lt;badgeCount&gt;.
        /// </summary>
        internal static string BWSCommandUsage {
            get {
                return ResourceManager.GetString("BWSCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Info.
        /// </summary>
        internal static string CommandInfo {
            get {
                return ResourceManager.GetString("CommandInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Disabled.
        /// </summary>
        internal static string CommandIsDisabled {
            get {
                return ResourceManager.GetString("CommandIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command List.
        /// </summary>
        internal static string CommandList {
            get {
                return ResourceManager.GetString("CommandList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Type.
        /// </summary>
        internal static string CommandType {
            get {
                return ResourceManager.GetString("CommandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string CommandUsage {
            get {
                return ResourceManager.GetString("CommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createapiuser.
        /// </summary>
        internal static string CreateAPIUserCommand {
            get {
                return ResourceManager.GetString("CreateAPIUserCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API user and key already exists.
        /// </summary>
        internal static string CreateAPIUserCommandAlreadyCreated {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API user and key created.
        /// </summary>
        internal static string CreateAPIUserCommandCreated {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an API user and key.
        /// </summary>
        internal static string CreateAPIUserCommandDescription {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key is:.
        /// </summary>
        internal static string CreateAPIUserCommandKey {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Uri is: http://dra-gon.wtf:40005/
        ///(you need to include the port!)
        ///Never share your key in public!
        ///You can share this key with trustworthy people, if it happens to get public or you need to revoke/change it, contact ??????#0284
        ///Incase of **abuse** or **willingly** sharing it in public, you might get blacklisted from the API (permanently) (trying to bypass this will result in a complete ban from using the bot!).
        /// </summary>
        internal static string CreateAPIUserCommandNeverShare {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandNeverShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}createapiuser.
        /// </summary>
        internal static string CreateAPIUserCommandUsage {
            get {
                return ResourceManager.GetString("CreateAPIUserCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to embed.
        /// </summary>
        internal static string EmbedCommand {
            get {
                return ResourceManager.GetString("EmbedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the discord channel.
        /// </summary>
        internal static string EmbedCommandChannelNotFound {
            get {
                return ResourceManager.GetString("EmbedCommandChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or edit embeds.
        /// </summary>
        internal static string EmbedCommandDescription {
            get {
                return ResourceManager.GetString("EmbedCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid link.
        /// </summary>
        internal static string EmbedCommandInvalidUri {
            get {
                return ResourceManager.GetString("EmbedCommandInvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed json not found.
        /// </summary>
        internal static string EmbedCommandJsonNotFound {
            get {
                return ResourceManager.GetString("EmbedCommandJsonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse embed json.
        /// </summary>
        internal static string EmbedCommandJsonNotParsable {
            get {
                return ResourceManager.GetString("EmbedCommandJsonNotParsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed modified.
        /// </summary>
        internal static string EmbedCommandModified {
            get {
                return ResourceManager.GetString("EmbedCommandModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Embed.
        /// </summary>
        internal static string EmbedCommandSent {
            get {
                return ResourceManager.GetString("EmbedCommandSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}embed create &lt;channel&gt; &lt;urlToEmbedJson&gt;
        ///{prefix}embed edit &lt;messageLink&gt; &lt;urlToEmbedJson&gt;
        ///{prefix}embed webhook &lt;channel&gt; &lt;urlToEmbedJson&gt; &lt;username&gt; [avatarLink]
        ///
        ///Embed Visualizer: &lt;https://leovoel.github.io/embed-visualizer/&gt;.
        /// </summary>
        internal static string EmbedCommandUsage {
            get {
                return ResourceManager.GetString("EmbedCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a command list or infos about a specific command.
        /// </summary>
        internal static string HelpCommandDescription {
            get {
                return ResourceManager.GetString("HelpCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; &gt; = required
        ///[ ] = optional
        //// = choose between
        ///!! !! = atleast one marked parameter required.
        /// </summary>
        internal static string HelpCommandFooter {
            get {
                return ResourceManager.GetString("HelpCommandFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string HelpCommandNotice {
            get {
                return ResourceManager.GetString("HelpCommandNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string HelpCommandPage {
            get {
                return ResourceManager.GetString("HelpCommandPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}help [page]
        ///{prefix}help &lt;command&gt;.
        /// </summary>
        internal static string HelpCommandUsage {
            get {
                return ResourceManager.GetString("HelpCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance.
        /// </summary>
        internal static string MaintenanceCommand {
            get {
                return ResourceManager.GetString("MaintenanceCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the maintenance message/status.
        /// </summary>
        internal static string MaintenanceCommandDescription {
            get {
                return ResourceManager.GetString("MaintenanceCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse status.
        /// </summary>
        internal static string MaintenanceCommandFailedParseStatus {
            get {
                return ResourceManager.GetString("MaintenanceCommandFailedParseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set status to: {0} and message to: {1}.
        /// </summary>
        internal static string MaintenanceCommandSetStatus {
            get {
                return ResourceManager.GetString("MaintenanceCommandSetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}maintenance &lt;status&gt; &lt;message&gt;.
        /// </summary>
        internal static string MaintenanceCommandUsage {
            get {
                return ResourceManager.GetString("MaintenanceCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permission.
        /// </summary>
        internal static string PermissionCommand {
            get {
                return ResourceManager.GetString("PermissionCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Level {0} not found!.
        /// </summary>
        internal static string PermissionCommandAccessLevelNotFound {
            get {
                return ResourceManager.GetString("PermissionCommandAccessLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission bind already exists.
        /// </summary>
        internal static string PermissionCommandBindAlreadyExists {
            get {
                return ResourceManager.GetString("PermissionCommandBindAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binded access level {0} to role {1}.
        /// </summary>
        internal static string PermissionCommandBinded {
            get {
                return ResourceManager.GetString("PermissionCommandBinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binds or unbinds a permission.
        /// </summary>
        internal static string PermissionCommandDescription {
            get {
                return ResourceManager.GetString("PermissionCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough permissions.
        /// </summary>
        internal static string PermissionCommandInsufficientPermission {
            get {
                return ResourceManager.GetString("PermissionCommandInsufficientPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission binds found.
        /// </summary>
        internal static string PermissionCommandNoPermissionsFound {
            get {
                return ResourceManager.GetString("PermissionCommandNoPermissionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord Role {0} not found!.
        /// </summary>
        internal static string PermissionCommandRoleNotFound {
            get {
                return ResourceManager.GetString("PermissionCommandRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbinded {0} permissions from role {1}.
        /// </summary>
        internal static string PermissionCommandUnbinded {
            get {
                return ResourceManager.GetString("PermissionCommandUnbinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}permission bind &lt;discordRoleId&gt; &lt;accessLevel&gt;
        ///{prefix}permission unbind &lt;discordRoleId&gt; [accessLevel].
        /// </summary>
        internal static string PermissionCommandUsage {
            get {
                return ResourceManager.GetString("PermissionCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy.
        /// </summary>
        internal static string PrivacyPolicyCommand {
            get {
                return ResourceManager.GetString("PrivacyPolicyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the bots privacy policy.
        /// </summary>
        internal static string PrivacyPolicyCommandDescription {
            get {
                return ResourceManager.GetString("PrivacyPolicyCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy
        ///```
        ///The following data is collected:
        ///Your Discord user data (username, ID, mention, roles)
        ///Your osu! data (username, ID, Scores)
        ///This data is used to verify users, analyze tournament matches, deliver tourney stats and improve the general discord user feeling
        ///
        ///
        ///If you have any questions or want your data deleted contact me on discord: ??????#0284
        ///I will try to answer withing 48 hours
        ///(If you request the deletion of your data, your data will be deleted and you will be blacklisted from [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicyCommandPrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicyCommandPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}privacy.
        /// </summary>
        internal static string PrivacyPolicyCommandUsage {
            get {
                return ResourceManager.GetString("PrivacyPolicyCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered {0} for discord command exceptions.
        /// </summary>
        internal static string RegisteredCommand {
            get {
                return ResourceManager.GetString("RegisteredCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removematch.
        /// </summary>
        internal static string RemoveMatchCommand {
            get {
                return ResourceManager.GetString("RemoveMatchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a match from the analyzer db.
        /// </summary>
        internal static string RemoveMatchCommandDescription {
            get {
                return ResourceManager.GetString("RemoveMatchCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed match .
        /// </summary>
        internal static string RemoveMatchCommandSuccess {
            get {
                return ResourceManager.GetString("RemoveMatchCommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}removematch &lt;matchId&gt;.
        /// </summary>
        internal static string RemoveMatchCommandUsage {
            get {
                return ResourceManager.GetString("RemoveMatchCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stats.
        /// </summary>
        internal static string StatsCommand {
            get {
                return ResourceManager.GetString("StatsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays stats for players/teams/matches.
        /// </summary>
        internal static string StatsCommandDescription {
            get {
                return ResourceManager.GetString("StatsCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}stats p/player p/profile osuUserId/osuUsername
        ///{prefix}stats p/player t/top [page]
        ///
        ///{prefix}stats t/team p/profile osuUserId/osuUsername
        ///{prefix}stats t/team t/top [page]
        ///
        ///{prefix}stats m/match &lt;matchId&gt;
        ///{prefix}stats m/match &lt;team a&gt; vs &lt;team b&gt;.
        /// </summary>
        internal static string StatsCommandUsage {
            get {
                return ResourceManager.GetString("StatsCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        internal static string SyncCommand {
            get {
                return ResourceManager.GetString("SyncCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup a config first.
        /// </summary>
        internal static string SyncCommandConfigNotSetup {
            get {
                return ResourceManager.GetString("SyncCommandConfigNotSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizes you/Mod: Force synchronize someone.
        /// </summary>
        internal static string SyncCommandDescription {
            get {
                return ResourceManager.GetString("SyncCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized .
        /// </summary>
        internal static string SyncCommandSyncSuccess {
            get {
                return ResourceManager.GetString("SyncCommandSyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}sync
        ///
        ///Moderator:
        ///{prefix}sync [discordUserId/Mention].
        /// </summary>
        internal static string SyncCommandUsage {
            get {
                return ResourceManager.GetString("SyncCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to verify yourself first!.
        /// </summary>
        internal static string SyncCommandVerifySelfFirst {
            get {
                return ResourceManager.GetString("SyncCommandVerifySelfFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ticket.
        /// </summary>
        internal static string TicketCommand {
            get {
                return ResourceManager.GetString("TicketCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to write or manage tickets.
        /// </summary>
        internal static string TicketCommandDescription {
            get {
                return ResourceManager.GetString("TicketCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}ticket ticket text
        ///
        ///
        ///Moderator:
        ///{prefix}ticket -get s/m(s/m, Single or Multisearch) page(value, Page Number) -id(+value, Ticket Id) -uid(+value, Discord User Id) -tag(+value, Ticket Tag) -status(+value, Ticket Status) -priority(+value, Ticket Priority) -sbn(value, Sort By Newest) -sbo(value, Sort By Oldest)
        ///{prefix}ticket -set id(value, Ticket Id) -status(+value, Ticket status) -priority(+value, Ticket priority) -tag(+value, ticket tag)
        ///
        ///
        ///Note:
        ///+value = identifier value
        ///value = valueItself.
        /// </summary>
        internal static string TicketCommandUsage {
            get {
                return ResourceManager.GetString("TicketCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verify.
        /// </summary>
        internal static string VerifyCommand {
            get {
                return ResourceManager.GetString("VerifyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify yourself.
        /// </summary>
        internal static string VerifyCommandDescription {
            get {
                return ResourceManager.GetString("VerifyCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}verify.
        /// </summary>
        internal static string VerifyCommandUsage {
            get {
                return ResourceManager.GetString("VerifyCommandUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warmup.
        /// </summary>
        internal static string WarmupCommand {
            get {
                return ResourceManager.GetString("WarmupCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added/Deleted maps.
        /// </summary>
        internal static string WarmupCommandConfirmation {
            get {
                return ResourceManager.GetString("WarmupCommandConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove warmup maps.
        /// </summary>
        internal static string WarmupCommandDescription {
            get {
                return ResourceManager.GetString("WarmupCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {prefix}warmup add &lt;beatmapId&gt; [beatmapId] [etc.]
        ///{prefix}warmup remove &lt;beatmapId&gt; [beatmapId] [etc.].
        /// </summary>
        internal static string WarmupCommandUsage {
            get {
                return ResourceManager.GetString("WarmupCommandUsage", resourceCulture);
            }
        }
    }
}
